GET http://jsonplaceholder.typicode.com/posts

###

POST http:GET http://jsonplaceholder.typicode.com/posts
//jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title": "New Post",
    "body": "This is a new post."
}
